const updateDeleteCommentTypes = {
  START_DELETE_COMMENT: 'START_DELETE_COMMENT',
  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',
  START_UPDATE_COMMENT: 'START_UPDATE_COMMENT',
  UPDATE_COMMENT_SUCCESS: 'UPDATE_COMMENT_SUCCESS',
  UPDATE_COMMENT_FAILURE: 'UPDATE_COMMENT_FAILURE',
  UPDATE_LAST_COMMENT_SUCCESS: 'UPDATE_LAST_COMMENT_SUCCESS',
  UPDATE_LAST_COMMENT_FAILURE: 'UPDATE_LAST_COMMENT_FAILURE'
};

export default updateDeleteCommentTypes;
