const setCommentTypes = {
  START_COMMENT: 'START_COMMENT',
  COMMENT_SUCCESS: 'COMMENT_SUCCESS',
  COMMENT_FAILURE: 'COMMENT_FAILURE',
  START_COMMENT_RATING: 'START_COMMENT_RATING',
  COMMENT_RATING_SUCCESS: 'COMMENT_RATING_SUCCESS'
};

export default setCommentTypes;
