const passwordRessetTypes = {
  START_PASSWORD_RESSET: 'START_PASSWORD_RESSET',
  PASSWORD_RESSET_SUCCESS: 'PASSWORD_RESSET_SUCCESS',
  PASSWORD_RESSET_FAILURE: 'PASSWORD_RESSET_FAILURE'
};

export default passwordRessetTypes;
