const placesActionTypes = {
  START_FETCH_PLACES_WITHIN: 'START_FETCH_PLACES_WITHIN',
  START_FETCH_PLACES_WITHIN_SUCCESS: 'START_FETCH_PLACES_WITHIN_SUCCESS',
  START_FETCH_PLACES_WITHIN_FAILURE: 'START_FETCH_PLACES_WITHIN_FAILURE'
};

export default placesActionTypes;
