const updateDeletePlaceTypes = {
  UPDATE_PLACE_START: 'UPDATE_PLACE_START',
  UPDATE_PLACE_SUCCESS: 'UPDATE_PLACE_SUCCESS',
  UPDATE_PLACE_FAILURE: 'UPDATE_PLACE_FAILURE',
  DELETE_PLACE_START: 'DELETE_PLACE_START',
  DELETE_PLACE_SUCCESS: 'DELETE_PLACE_SUCCESS',
  DELETE_PLACE_FAILURE: 'DELETE_PLACE_FAILURE'
};

export default updateDeletePlaceTypes;
