const userActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_CURRENT_USER_SUCCESS_LOGIN: 'SET_CURRENT_USER_SUCCESS_LOGIN',
  SET_CURRENT_USER_FAILURE_LOGIN: 'SET_CURRENT_USER_FAILURE_LOGIN',
  SET_CURRENT_USER_SUCCESS_SIGNUP: 'SET_CURRENT_USER_SUCCESS_SIGNUP',
  SET_CURRENT_USER_FAILURE_SIGNUP: 'SET_CURRENT_USER_FAILURE_SIGNUP',
  SET_CURRENT_USER_SUCCESS_UPLOAD: 'SET_CURRENT_USER_SUCCESS_UPLOAD',
  SET_CURRENT_USER_FAILURE_UPLOAD: 'SET_CURRENT_USER_FAILURE_UPLOAD',
  SET_CURRENT_USER_UPLOAD: 'SET_CURRENT_USER_UPLOAD',
  SET_USER_START: 'SET_USER_START',
  SIGNOUT_START: 'SIGNOUT_START',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
  SIGNUP_START: 'SIGNUP_START',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  CLEAR_ERRORS_SUCCESS: 'CLEAR_ERRORS_SUCCESS',
  UPLOAD_START: 'UPDATE_START',
  UPLOAD_SUCCESS: 'UPDATE_SUCCESS',
  UPLOAD_FAILURE: 'UPDATE_FAILURE',
  SET_CHANGE_ENBALED_SUCCESS: 'SET_CHANGE_ENBALED_SUCCESS',
  SET_CHANGE_ENABLED_START: 'SET_CHANGE_ENABLED_START',
  SET_CHANGE_ENABLED_FAILURE: 'SET_CHANGE_ENABLED_FAILURE'
};

export default userActionTypes;
