const userActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_USER_START: 'SET_USER_START',
  SET_USER_SUCCESS: 'SET_USER_SUCCESS',
  SET_USER_FAILURE: 'SET_USER_FAILURE',
  SIGNOUT_START: 'SIGNOUT_START',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE'
};

export default userActionTypes;
