const coordsActionTypes = {
  START_FETCH_COORDS: 'START_FETCH_COORDS',
  FETCH_COORDS_SUCCESS: 'FETCH_COORDS_SUCCESS',
  FETCH_COORDS_ERROR: 'FETCH_COORDS_ERROR',
  START_NAME: 'START_NAME',
  SET_NAME_SUCCESS: 'SET_NAME_SUCCESS',
  SET_NAME_FAILURE: 'SET_NAME_FAILURE',
  START_DESC: 'START_DESC',
  SET_DESC_SUCCESS: 'SET_DESC_SUCCESS',
  SET_DESC_FAILURE: 'SET_DESC_FAILURE',
  START_PHOTO: 'START_PHOTO',
  PHOTO_SUCCESS: 'PHOTO_SUCCESS',
  PHOTO_FAILURE: 'PHOTO_FAILURE',
  RATING_START: 'RATING_START',
  RATING_SUCCESS: 'RATING_SUCCESS',
  RATING_FAILURE: 'RATING_FAILURE',
  START_SET_ADDRESS: 'START_SET_ADDRESS',
  SET_ADDRESS_SUCCESS: 'SET_ADDRESS_SUCCESS',
  SET_ADDRESS_FAILURE: 'SET_ADDRESS_FAILURE'
};

export default coordsActionTypes;
